name = "iris-ai-vm"
main = "src/worker.js"
compatibility_date = "2026-06-15"

[[build.upload.rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[assets]
directory = "./public"

[observability]
enabled = true
