name = "iris-devbox"
main = "src/worker.js"
compatibility_date = "2026-06-15"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[assets]
directory = "./public"

[observability]
enabled = true
